### ISSUE TITLE
tvOS SDK is never ready for display

### ISSUE THREAD

**Issue by tiagomartinho** [AppLovin/tvOS-Demo-App#2]
Both with the Objective-C and Swift sample projects the app is never ready to show advertising.

I integrated without problems the SDK with my iOS app so I can exclude the problem of the SDK key.

I tried both on the Device and the Simulator.

Any ideas?

![Uploading Simulator Screen Shot 2 Dec 2016, 18.46.33.png…]()

**Comment by thomasmso** [comment]
Hi,

Thanks for reaching out. Your problem might be caused by a lack of active campaigns targeting your locale.

**Comment by tiagomartinho** [comment]
Hi, even if it displays ads on the iOS version? 
Should I ship it and see if it works on others locale?

**Comment by thomasmso** [comment]
Correct. iOS and tvOS advertising campaigns are managed separately by the advertisers.
