### ISSUE TITLE
Can not find libAppLovinTVOS.a in the Download SDK link

### ISSUE THREAD

**Issue by billypchan** [AppLovin/tvOS-Demo-App#3]
Hi,
The link to the Download page open the page for Android integration. Is there updated link? Thanks!

**Comment by thomasmso** [comment]
Hi, 

We no longer support tvOS.

**Comment by Sebacho-Barajas** [comment]
@thomasmso any reason for not supporting it anymore?

**Comment by thomasmso** [comment]
Primarily management decision due to low demand.
